export enum EmailTypesEnum {
  CODE,
  REGISTER,
  FORGOTTEN_PASSWORD,
  CHANGE_PASSWORD,
  RESERVATION_CREATED,
  RESERVATION_IS_GOING_TO_EXPIRE,
  RESERVATION_EXPIRED,
  LIQUIDATION_GENERATED,
  _,
  __,
  REQUEST_CREATED,
  REQUEST_PARKING_DETAILS_FORM,
  REQUEST_CALENDAR_FORM,
  REQUEST_FINALIZED,
  REQUEST_CANCELED
}
