AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: CreateBookingSchedule
      Role: arn:aws:iam::175445123792:role/AWSParkeateLambdaExecutionRole
      Code:
        ImageUri: 175445123792.dkr.ecr.sa-east-1.amazonaws.com/create-booking-schedule-yfx:latest
      PackageType: Image
      MemorySize: 128
      Timeout: 60
      Environment:
        Variables:
          LOG_LEVEL: INFO
