AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: ParkeateMultiFunctionLambdaPipeline
      RoleArn: arn:aws:iam::175445123792:role/AWSCodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: lambda-cf-artifacts
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: parkeate-lambda-functions
                BranchName: main
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: BuildGetZipFromS3FolderYFX
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: BuildGetZipFromS3FolderYFX
                PrimarySource: SourceArtifact
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildGetZipFromS3Folder-YFX-ARTIFACT

            - Name: BuildGetViewSignedUrlYFX
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: BuildGetViewSignedUrlYFX
                PrimarySource: SourceArtifact
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildGetViewSignedUrlYFX-YFX-ARTIFACT
        - Name: Deploy
          Actions:
            - Name: DeployGetZipFromS3FolderYFX
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: arn:aws:iam::175445123792:role/AWSCloudFormationExecutionRole
                StackName: LambdaDockerStackGetZipFromS3Folder-YFX
                ChangeSetName: LambdaDockerStackGetZipFromS3Folder-YFX
                Capabilities: CAPABILITY_IAM
                TemplatePath: BuildGetZipFromS3Folder-YFX-ARTIFACT::getZipFromS3Folder/template.yml
              InputArtifacts:
                - Name: BuildGetZipFromS3Folder-YFX-ARTIFACT

            - Name: DeployGetViewSignedUrlYFX
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: arn:aws:iam::175445123792:role/AWSCloudFormationExecutionRole
                StackName: LambdaDockerStackGetViewSignedUrl-YFX
                ChangeSetName: LambdaDockerStackGetViewSignedUrl-YFX
                Capabilities: CAPABILITY_IAM
                TemplatePath: BuildGetViewSignedUrlYFX-YFX-ARTIFACT::getViewSignedUrl/template.yml
              InputArtifacts:
                - Name: BuildGetViewSignedUrlYFX-YFX-ARTIFACT

  BuildProjectGetZipFromS3FolderYFX:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: BuildGetZipFromS3FolderYFX
      Source:
        Type: CODEPIPELINE
        BuildSpec: getZipFromS3Folder/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::175445123792:role/AWSCodeBuildParkeateMultiFunctionPipeline

  BuildProjectGetViewSignedUrlYFX:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: BuildGetViewSignedUrlYFX
      Source:
        Type: CODEPIPELINE
        BuildSpec: getViewSignedUrl/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::175445123792:role/AWSCodeBuildParkeateMultiFunctionPipeline

  ECRRepositoryGetZipFromS3FolderYFX:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: get-zip-from-s3-folder-yfx
  ECRRepositoryGetViewSignedUrlYFX:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: get-view-signed-url-yfx
#  ECRRepositoryFunction2:
#    Type: AWS::ECR::Repository
#    Properties:
#      RepositoryName: function-2
