AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: ParkeateMultiFunctionLambdaPipeline
      RoleArn: arn:aws:iam::175445123792:role/AWSCodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: lambda-cf-artifacts
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: parkeate-lambda-functions
                BranchName: main
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: BuildGetZipFromS3FolderYFX
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: BuildGetZipFromS3FolderYFX
                PrimarySource: SourceArtifact
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildGetZipFromS3Folder-YFX-ARTIFACT

            - Name: BuildGetViewSignedUrlYFX
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: BuildGetViewSignedUrlYFX
                PrimarySource: SourceArtifact
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildGetViewSignedUrl-YFX-ARTIFACT

            - Name: BuildGetSignedUrlYFX
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: BuildGetSignedUrlYFX
                PrimarySource: SourceArtifact
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildGetSignedUrl-YFX-ARTIFACT

            - Name: BuildUpdateBookingStatusYFX
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: BuildUpdateBookingStatusYFX
                PrimarySource: SourceArtifact
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildUpdateBookingStatus-YFX-ARTIFACT

            - Name: BuildCreateBookingScheduleYFX
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: BuildCreateBookingScheduleYFX
                PrimarySource: SourceArtifact
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildCreateBookingSchedule-YFX-ARTIFACT

        - Name: Deploy
          Actions:
            - Name: DeployGetZipFromS3FolderYFX
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: arn:aws:iam::175445123792:role/AWSCloudFormationExecutionRole
                StackName: LambdaDockerStackGetZipFromS3Folder-YFX
                ChangeSetName: LambdaDockerStackGetZipFromS3Folder-YFX
                Capabilities: CAPABILITY_IAM
                TemplatePath: BuildGetZipFromS3Folder-YFX-ARTIFACT::getZipFromS3Folder/template.yml
              InputArtifacts:
                - Name: BuildGetZipFromS3Folder-YFX-ARTIFACT

            - Name: DeployGetViewSignedUrlYFX
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: arn:aws:iam::175445123792:role/AWSCloudFormationExecutionRole
                StackName: LambdaDockerStackGetViewSignedUrl-YFX
                ChangeSetName: LambdaDockerStackGetViewSignedUrl-YFX
                Capabilities: CAPABILITY_IAM
                TemplatePath: BuildGetViewSignedUrl-YFX-ARTIFACT::getViewSignedUrl/template.yml
              InputArtifacts:
                - Name: BuildGetViewSignedUrl-YFX-ARTIFACT

            - Name: DeployGetSignedUrlYFX
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: arn:aws:iam::175445123792:role/AWSCloudFormationExecutionRole
                StackName: LambdaDockerStackGetSignedUrl-YFX
                ChangeSetName: LambdaDockerStackGetSignedUrl-YFX
                Capabilities: CAPABILITY_IAM
                TemplatePath: BuildGetSignedUrl-YFX-ARTIFACT::getSignedUrl/template.yml
              InputArtifacts:
                - Name: BuildGetSignedUrl-YFX-ARTIFACT

            - Name: DeployUpdateBookingStatusYFX
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: arn:aws:iam::175445123792:role/AWSCloudFormationExecutionRole
                StackName: LambdaDockerStackUpdateBookingStatus-YFX
                ChangeSetName: LambdaDockerStackUpdateBookingStatus-YFX
                Capabilities: CAPABILITY_IAM
                TemplatePath: BuildUpdateBookingStatus-YFX-ARTIFACT::updateBookingStatus/template.yml
              InputArtifacts:
                - Name: BuildUpdateBookingStatus-YFX-ARTIFACT

            - Name: DeployCreateBookingScheduleYFX
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: arn:aws:iam::175445123792:role/AWSCloudFormationExecutionRole
                StackName: LambdaDockerStackCreateBookingSchedule-YFX
                ChangeSetName: LambdaDockerStackCreateBookingSchedule-YFX
                Capabilities: CAPABILITY_IAM
                TemplatePath: BuildCreateBookingSchedule-YFX-ARTIFACT::createBookingSchedule/template.yml
              InputArtifacts:
                - Name: BuildCreateBookingSchedule-YFX-ARTIFACT

  BuildProjectGetZipFromS3FolderYFX:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: BuildGetZipFromS3FolderYFX
      Source:
        Type: CODEPIPELINE
        BuildSpec: getZipFromS3Folder/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::175445123792:role/AWSCodeBuildParkeateMultiFunctionPipeline

  BuildProjectGetViewSignedUrlYFX:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: BuildGetViewSignedUrlYFX
      Source:
        Type: CODEPIPELINE
        BuildSpec: getViewSignedUrl/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::175445123792:role/AWSCodeBuildParkeateMultiFunctionPipeline

  BuildProjectGetSignedUrlYFX:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: BuildGetSignedUrlYFX
      Source:
        Type: CODEPIPELINE
        BuildSpec: getSignedUrl/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::175445123792:role/AWSCodeBuildParkeateMultiFunctionPipeline

  BuildProjectUpdateBookingStatusYFX:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: BuildUpdateBookingStatusYFX
      Source:
        Type: CODEPIPELINE
        BuildSpec: updateBookingStatus/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::175445123792:role/AWSCodeBuildParkeateMultiFunctionPipeline

  BuildProjectCreateBookingScheduleYFX:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: BuildCreateBookingScheduleYFX
      Source:
        Type: CODEPIPELINE
        BuildSpec: createBookingSchedule/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::175445123792:role/AWSCodeBuildParkeateMultiFunctionPipeline

  ECRRepositoryGetZipFromS3FolderYFX:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: get-zip-from-s3-folder-yfx

  ECRRepositoryGetViewSignedUrlYFX:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: get-view-signed-url-yfx

  ECRRepositoryGetSignedUrlYFX:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: get-signed-url-yfx

  ECRRepositoryUpdateBookingStatusYFX:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: update-booking-status-yfx

  ECRRepositoryCreateBookingScheduleYFX:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: create-booking-schedule-yfx