export enum BanksEnum {
  BANCO_ESTADO,
  BANCO_DE_CHILE_EDWARDS_CITI,
  BANCO_SANTANDER,
  BANCO_BICE,
  BANCO_CONSORCIO,
  BANCO_FALABELLA,
  BANCO_ITAU,
  BANCO_RIPLEY,
  BANCO_SANTANDER_BANEFE,
  BANCO_SECURITY,
  BCI,
  BCI_TBANC,
  CORPBANCA,
  PREPAGO_LOS_HEROES,
  SCOTIABANK,
  SCOTIABANK_AZUL,
}
export const BankNames = [
  "Banco Estado",
  "Banco de Chile / Edwards Citi",
  "Banco Santander",
  "Banco Bice",
  "Banco Consorcio",
  "Banco Falabella",
  "Banco Itau",
  "Banco Ripley",
  "Banco Santander Banefe",
  "Banco Security",
  "BCI",
  "BCI-TBANC",
  "CorpBanca",
  "Prepago Los Héroes",
  "Scotiabank",
  "Scotiabank Azul",
];
export enum BankAccountTypeEnum {
  CUENTA_CORRIENTE,
  CUENTA_VISTA,
  CHEQUERA_ELECTRONICA,
  CUENTA_DE_AHORRO,
}
export const BankAccountTypeNameEnum = [
  "Cuenta Corriente",
  "Cuenta Vista",
  "Chequera Electronica",
  "Cuenta de Ahorro",
];
